name: Sync Roadmap

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.OTELBOT_ROADMAP_APP_ID }}
          private-key: ${{ secrets.OTELBOT_ROADMAP_PRIVATE_KEY }}

      - name: Run sync script
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: python scripts/sync_roadmap.py
